name: Android Build

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Fix gradlew permissions
        run: chmod +x ./gradlew

      # ВАЖНО:
      # фикс поврежденных JVM args в gradlew
      - name: Fix gradlew JVM opts
        run: |
          sed -i 's/DEFAULT_JVM_OPTS=.*/DEFAULT_JVM_OPTS=""/g' gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NEXTVM-debug
          path: |
            app/build/outputs/apk/debug/*.apk
            */build/outputs/apk/debug/*.apk
